const TYPES = {
  GET_STUDENTS: `GET_STUDENTS`,
  GET_CLASSES: `GET_CLASSES`,
  GET_HOUSES: `GET_HOUSES`,
  ADD_STUDENT: "ADD_STUDENT",
  ADD_CLASS: "ADD_CLASS",
  GET_CLASSES_STUDENTS: "GET_CLASSES_STUDENTS",
  CLEAR_INPUT: "CLEAR_INPUT",
  ENROLL_STUDENT: "ENROLL_STUDENT",
  ADD_CLASSES_STUDENTS: "ADD_CLASSES_STUDENTS",
  GET_STUDENT_COUNT: "GET_STUDENT_COUNT",
  GET_CLASSES_COUNT: "GET_CLASSES_COUNT",
  GET_ALL_STUDENTS: "GET_ALL_STUDENTS",
  GET_ALL_CLASSES: "GET_ALL_CLASSES",
  UPDATE_INPUT:'UPDATE_INPUT'
};

module.exports = TYPES;
